"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['VanasMetaID3.py']
DATA_FILES = []
OPTIONS = {
    'iconfile':'images/vanasid3.icns',
    'resources':'images'
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
